yarnPath: ".yarn/releases/yarn-berry.cjs"

# pnpMode: "loose"

packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    peerDependencies:
      typescript: "*"
#   "@putout/engine-loader@*":
#     peerDependencies:
#       "@babel/preset-env": ^7.1.6
#       "@babel/types": "*"
#   "@putout/engine-parser@*":
#     peerDependencies:
#       "@babel/types": "*"
#   "@putout/engine-processor@*":
#     peerDependencies:
#       "@babel/types": "*"
  "@shopify/eslint-plugin@*":
    peerDependencies:
      eslint-config-prettier: "*"
      # eslint-import-resolver-node: "*"
      eslint-plugin-prettier: "*"
      eslint-plugin-promise: "*"
      graphql: "*"
      prettier: "*"
      typescript: "*"
#   debug@*:
#     peerDependencies:
#       supports-color: "*"
  eslint-config-hardcore@*:
    peerDependencies:
      # "@babel/preset-env": ^7.1.6
      "@emotion/eslint-plugin": "*"
      "@shopify/eslint-plugin": "*"
      eslint-config-prettier: "*"
      # eslint-import-resolver-node: "*"
      eslint-plugin-array-func: "*"
      eslint-plugin-eslint-comments: "*"
      eslint-plugin-ext: "*"
      eslint-plugin-import: "*"
      eslint-plugin-json: ^2.1.2
      eslint-plugin-no-use-extend-native: "*"
      eslint-plugin-optimize-regex: "*"
      eslint-plugin-prettier: "*"
      eslint-plugin-promise: "*"
      eslint-plugin-putout: "*"
      eslint-plugin-regexp: "*"
      eslint-plugin-security: "*"
      eslint-plugin-sonarjs: "*"
      eslint-plugin-unicorn: "*"
      graphql: "*"
      putout: "*"
#   eslint-module-utils@*:
#     peerDependencies:
#       eslint-import-resolver-node: "*"
  eslint-plugin-graphql@*:
    peerDependencies:
      typescript: "*"
  eslint-plugin-import@*:
    peerDependencies:
      eslint-import-resolver-node: "*"
#   eslint-plugin-sonarjs@*:
#     peerDependencies:
#       eslint: "7"
  graphql-config@*:
    peerDependencies:
      typescript: "*"
#   next@*:
#     peerDependencies:
#       webpack: 4.44.1
#   next-svgr@*:
#     peerDependencies:
#       "@svgr/webpack": "*"
#   putout@*:
#     peerDependencies:
#       "@babel/preset-env": ^7.1.6
