nodeLinker: node-modules

packageExtensions:
  "@microsoft/eslint-plugin-sdl@0.2":
    peerDependencies:
      eslint: "*"
  "@shopify/eslint-plugin@43":
    peerDependencies:
      "@babel/core": "*"
      prettier: "*"
  eslint-config-hardcore@41:
    peerDependencies:
      "@babel/core": "*"
      "@testing-library/dom": "*"
      vue-eslint-parser: "*"
  eslint-plugin-sonar@0.12:
    peerDependencies:
      "@babel/core": "*"
      "@typescript-eslint/parser": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.6.3.cjs
