packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    peerDependencies:
      typescript: "*"
  "@putout/compare@*":
    peerDependencies:
      try-catch: "*"
  "@putout/engine-loader@*":
    peerDependencies:
      "@babel/preset-env": "*"
  "@putout/engine-parser@*":
    peerDependencies:
      try-catch: "*"
  "@putout/engine-processor@*":
    peerDependencies:
      "@babel/preset-env": "*"
  "@putout/traverse@*":
    peerDependencies:
      try-catch: "*"
  "@shopify/eslint-plugin@*":
    peerDependencies:
      eslint-config-prettier: "*"
      eslint-plugin-prettier: "*"
      eslint-plugin-promise: "*"
      graphql: "*"
      prettier: "*"
      typescript: "*"
  eslint-config-hardcore@*:
    peerDependencies:
      "@emotion/eslint-plugin": "*"
      "@shopify/eslint-plugin": "*"
      eslint-config-prettier: "*"
      eslint-plugin-array-func: "*"
      eslint-plugin-eslint-comments: "*"
      eslint-plugin-ext: "*"
      eslint-plugin-import: "*"
      eslint-plugin-json: ^2.1.2
      eslint-plugin-no-use-extend-native: "*"
      eslint-plugin-optimize-regex: "*"
      eslint-plugin-prettier: "*"
      eslint-plugin-promise: "*"
      eslint-plugin-putout: "*"
      eslint-plugin-regexp: "*"
      eslint-plugin-security: "*"
      eslint-plugin-sonarjs: "*"
      eslint-plugin-unicorn: "*"
      graphql: "*"
      putout: "*"
  eslint-plugin-graphql@*:
    peerDependencies:
      typescript: "*"
  eslint-plugin-import@*:
    peerDependencies:
      eslint-import-resolver-node: "*"
  graphql-config@*:
    peerDependencies:
      typescript: "*"
  putout@*:
    peerDependencies:
      "@babel/preset-env": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.4.2.cjs
