packageExtensions:
  "@putout/engine-processor@4":
    peerDependencies:
      "@babel/preset-env": "*"
  "@shopify/eslint-plugin@42":
    peerDependencies:
      "@babel/core": "*"
      prettier: "*"
  eslint-config-hardcore@25:
    peerDependencies:
      "@babel/core": "*"
      "@babel/preset-env": "*"
  eslint-plugin-styled-components-a11y@1:
    peerDependencies:
      eslint-plugin-import: "*"
      eslint-plugin-react: "*"
      eslint: "*"
  putout@24:
    peerDependencies:
      "@babel/preset-env": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs

# https://github.com/benmosher/eslint-plugin-import/issues/2164
nodeLinker: node-modules
