nodeLinker: node-modules

packageExtensions:
  "@microsoft/eslint-plugin-sdl@0.2":
    peerDependencies:
      eslint: "*"
  "@putout/engine-processor@6":
    peerDependencies:
      putout: "*"
  "@putout/engine-runner@15":
    peerDependencies:
      putout: "*"
  "@shopify/eslint-plugin@42":
    peerDependencies:
      "@babel/core": "*"
      prettier: "*"
  eslint-config-hardcore@35:
    peerDependencies:
      "@babel/core": "*"
      vue-eslint-parser: "*"
  eslint-plugin-styled-components-a11y@0.1:
    peerDependencies:
      eslint: "*"
      eslint-plugin-import: "*"
      eslint-plugin-react: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.5.0.cjs
