packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@3":
    peerDependencies:
      typescript: "*"
  "@putout/engine-loader@4":
    peerDependencies:
      "@babel/preset-env": "*"
  "@putout/engine-processor@4":
    peerDependencies:
      "@babel/preset-env": "*"
  "@shopify/eslint-plugin@41":
    peerDependencies:
      "@babel/core": "*"
      graphql: "*"
      prettier: "*"
      typescript: "*"
  eslint-config-hardcore@24:
    peerDependencies:
      "@babel/core": "*"
      "@babel/preset-env": "*"
      graphql: "*"
  eslint-plugin-graphql@4:
    peerDependencies:
      typescript: "*"
  graphql-config@3:
    peerDependencies:
      typescript: "*"
  putout@24:
    peerDependencies:
      "@babel/preset-env": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs

# https://github.com/benmosher/eslint-plugin-import/issues/2164
nodeLinker: node-modules
